# Generated by Django 6.0.6 on 2026-08-29 19:43

import accounts.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FriendRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', '대기'), ('ACCEPTED', '수락'), ('REJECTED', '거절'), ('CANCELED', '취소')], default='PENDING', max_length=10, verbose_name='상태')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_friend_requests', to=settings.AUTH_USER_MODEL, verbose_name='수신자')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_friend_requests', to=settings.AUTH_USER_MODEL, verbose_name='요청자')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['receiver', 'status'], name='accounts_fr_receive_625767_idx'), models.Index(fields=['sender', 'status'], name='accounts_fr_sender__ee9283_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'PENDING')), fields=('sender', 'receiver'), name='unique_pending_friend_request'), models.CheckConstraint(condition=models.Q(('sender', models.F('receiver')), _negated=True), name='prevent_self_friend_request')],
            },
        ),
        migrations.CreateModel(
            name='Friendship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('friend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend_of', to=settings.AUTH_USER_MODEL, verbose_name='친구')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendships', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'created_at'], name='accounts_fr_user_id_2124b8_idx'), models.Index(fields=['friend', 'created_at'], name='accounts_fr_friend__5d2e42_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'friend'), name='unique_friendship'), models.CheckConstraint(condition=models.Q(('user', models.F('friend')), _negated=True), name='prevent_self_friendship')],
            },
        ),
        migrations.CreateModel(
            name='SocialAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('google', 'Google'), ('naver', 'Naver'), ('apple', 'Apple'), ('supabase', 'Supabase')], max_length=20, verbose_name='소셜 제공자')),
                ('provider_user_id', models.CharField(max_length=255, verbose_name='소셜 사용자 ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_accounts', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'ordering': ['created_at'],
                'constraints': [models.UniqueConstraint(fields=('provider', 'provider_user_id'), name='unique_social_account'), models.UniqueConstraint(fields=('user', 'provider'), name='unique_user_social_provider')],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(default=accounts.models.Get_Random_Nickname, max_length=30, verbose_name='닉네임')),
                ('nickname_tag', models.CharField(editable=False, max_length=5, unique=True, verbose_name='닉네임 태그')),
                ('bio', models.CharField(blank=True, default='', max_length=150, verbose_name='한 줄 소개')),
                ('profile_image_path', models.CharField(blank=True, default='', max_length=500, verbose_name='프로필 이미지 경로')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['nickname'], name='accounts_us_nicknam_f78a73_idx'), models.Index(fields=['nickname_tag'], name='accounts_us_nicknam_15a42d_idx')],
            },
        ),
    ]
