# Generated by Django 6.0.6 on 2026-08-30 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='한 줄 소개'),
        ),
    ]
