# Generated by Django 6.0.6 on 2026-09-17 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_userprofile_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialaccount',
            name='refresh_token',
            field=models.TextField(blank=True, null=True, verbose_name='OAuth Refresh Token'),
        ),
    ]
