# Generated by Django 6.0.6 on 2026-08-29 19:43

import django.db.models.deletion
import todos.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='태그 이름')),
                ('color', models.CharField(default='gray', max_length=20, verbose_name='태그 색상')),
                ('is_default', models.BooleanField(default=False, verbose_name='기본 태그 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='할 일 제목')),
                ('is_completed', models.BooleanField(default=False, verbose_name='완료 여부')),
                ('due_date', models.DateField(db_index=True, verbose_name='시작일')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='종료일')),
                ('todo_time', models.TimeField(default=todos.models.Get_Current_Time, verbose_name='할 일 시간')),
                ('is_time_manual', models.BooleanField(default=False, verbose_name='시간 직접 입력 여부')),
                ('priority', models.CharField(choices=[('H', '높음'), ('M', '보통'), ('L', '낮음')], default='M', max_length=1, verbose_name='우선순위')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='todos', to='todos.tag', verbose_name='태그')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todos', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='TodoCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_date', models.DateField(db_index=True, verbose_name='완료 날짜')),
                ('completed_at', models.DateTimeField(auto_now_add=True, verbose_name='완료 시간')),
                ('todo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='todos.todo', verbose_name='Todo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todo_completions', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'ordering': ['completed_date'],
            },
        ),
        migrations.CreateModel(
            name='TodoSomeday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='할 일 제목')),
                ('is_completed', models.BooleanField(default=False, verbose_name='완료 여부')),
                ('priority', models.CharField(choices=[('H', '높음'), ('M', '보통'), ('L', '낮음')], default='M', max_length=1, verbose_name='우선순위')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='someday_todos', to='todos.tag', verbose_name='태그')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='someday_todos', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'ordering': ['is_completed', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['user', 'created_at'], name='todos_tag_user_id_03ecee_idx'),
        ),
        migrations.AddConstraint(
            model_name='tag',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='unique_user_tag_name'),
        ),
        migrations.AddConstraint(
            model_name='tag',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('user',), name='unique_default_tag_per_user'),
        ),
        migrations.AddIndex(
            model_name='todo',
            index=models.Index(fields=['user', 'due_date'], name='todos_todo_user_id_b502e4_idx'),
        ),
        migrations.AddIndex(
            model_name='todo',
            index=models.Index(fields=['user', 'end_date'], name='todos_todo_user_id_d6607d_idx'),
        ),
        migrations.AddIndex(
            model_name='todo',
            index=models.Index(fields=['user', 'priority'], name='todos_todo_user_id_f95150_idx'),
        ),
        migrations.AddIndex(
            model_name='todocompletion',
            index=models.Index(fields=['user', 'completed_date'], name='todos_todoc_user_id_345e9d_idx'),
        ),
        migrations.AddIndex(
            model_name='todocompletion',
            index=models.Index(fields=['todo', 'completed_date'], name='todos_todoc_todo_id_86010b_idx'),
        ),
        migrations.AddConstraint(
            model_name='todocompletion',
            constraint=models.UniqueConstraint(fields=('todo', 'completed_date'), name='unique_todo_completion_date'),
        ),
        migrations.AddIndex(
            model_name='todosomeday',
            index=models.Index(fields=['user', 'created_at'], name='todos_todos_user_id_c096f8_idx'),
        ),
    ]
