# Generated by Django 6.0.6 on 2026-07-22 13:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='할 일 제목')),
                ('is_completed', models.BooleanField(default=False, verbose_name='완료 여부')),
                ('due_date', models.DateField(db_index=True, verbose_name='마감일')),
                ('priority', models.CharField(choices=[('H', '높음'), ('M', '보통'), ('L', '낮음')], default='M', max_length=1, verbose_name='우선순위')),
                ('tag', models.CharField(choices=[('WORK', '업무'), ('PERSONAL', '개인'), ('HEALTH', '건강'), ('STUDY', '공부'), ('ETC', '기타')], default='WORK', max_length=10, verbose_name='태그')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
