# Generated by Django 6.0.7 on 2026-08-19 05:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='태그 이름')),
                ('color', models.CharField(default='gray', max_length=20, verbose_name='태그 색상')),
                ('is_default', models.BooleanField(default=False, verbose_name='기본 태그 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='할 일 제목')),
                ('is_completed', models.BooleanField(default=False, verbose_name='완료 여부')),
                ('due_date', models.DateField(db_index=True, verbose_name='시작일')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='종료일')),
                ('priority', models.CharField(choices=[('H', '높음'), ('M', '보통'), ('L', '낮음')], default='M', max_length=1, verbose_name='우선순위')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='todos', to='todos.tag', verbose_name='태그')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todos', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='TodoCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_date', models.DateField(db_index=True, verbose_name='완료 날짜')),
                ('completed_at', models.DateTimeField(auto_now_add=True, verbose_name='완료 시간')),
                ('todo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='todos.todo', verbose_name='Todo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todo_completions', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'ordering': ['completed_date'],
            },
        ),
        migrations.CreateModel(
            name='TodoSomeday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='할 일 제목')),
                ('is_completed', models.BooleanField(default=False, verbose_name='완료 여부')),
                ('priority', models.CharField(choices=[('H', '높음'), ('M', '보통'), ('L', '낮음')], default='M', max_length=1, verbose_name='우선순위')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='someday_todos', to='todos.tag', verbose_name='태그')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='someday_todos', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'ordering': ['is_completed', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=30, verbose_name='닉네임')),
                ('nickname_tag', models.CharField(editable=False, max_length=5, unique=True, verbose_name='닉네임 태그')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='FriendRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', '대기'), ('ACCEPTED', '수락'), ('REJECTED', '거절'), ('CANCELED', '취소')], default='PENDING', max_length=10, verbose_name='상태')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_friend_requests', to=settings.AUTH_USER_MODEL, verbose_name='수신자')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_friend_requests', to=settings.AUTH_USER_MODEL, verbose_name='요청자')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['receiver', 'status'], name='todos_frien_receive_957841_idx'), models.Index(fields=['sender', 'status'], name='todos_frien_sender__3c8300_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'PENDING')), fields=('sender', 'receiver'), name='unique_pending_friend_request'), models.CheckConstraint(condition=models.Q(('sender', models.F('receiver')), _negated=True), name='prevent_self_friend_request')],
            },
        ),
        migrations.CreateModel(
            name='Friendship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('friend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend_of', to=settings.AUTH_USER_MODEL, verbose_name='친구')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendships', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'created_at'], name='todos_frien_user_id_d13804_idx'), models.Index(fields=['friend', 'created_at'], name='todos_frien_friend__4136fc_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'friend'), name='unique_friendship'), models.CheckConstraint(condition=models.Q(('user', models.F('friend')), _negated=True), name='prevent_self_friendship')],
            },
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['user', 'created_at'], name='todos_tag_user_id_03ecee_idx'),
        ),
        migrations.AddConstraint(
            model_name='tag',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='unique_user_tag_name'),
        ),
        migrations.AddConstraint(
            model_name='tag',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('user',), name='unique_default_tag_per_user'),
        ),
        migrations.AddIndex(
            model_name='todo',
            index=models.Index(fields=['user', 'due_date'], name='todos_todo_user_id_b502e4_idx'),
        ),
        migrations.AddIndex(
            model_name='todo',
            index=models.Index(fields=['user', 'end_date'], name='todos_todo_user_id_d6607d_idx'),
        ),
        migrations.AddIndex(
            model_name='todo',
            index=models.Index(fields=['user', 'priority'], name='todos_todo_user_id_f95150_idx'),
        ),
        migrations.AddIndex(
            model_name='todocompletion',
            index=models.Index(fields=['user', 'completed_date'], name='todos_todoc_user_id_345e9d_idx'),
        ),
        migrations.AddIndex(
            model_name='todocompletion',
            index=models.Index(fields=['todo', 'completed_date'], name='todos_todoc_todo_id_86010b_idx'),
        ),
        migrations.AddConstraint(
            model_name='todocompletion',
            constraint=models.UniqueConstraint(fields=('todo', 'completed_date'), name='unique_todo_completion_date'),
        ),
        migrations.AddIndex(
            model_name='todosomeday',
            index=models.Index(fields=['user', 'created_at'], name='todos_todos_user_id_c096f8_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['nickname'], name='todos_userp_nicknam_dce126_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['nickname_tag'], name='todos_userp_nicknam_6c3526_idx'),
        ),
    ]
