# Generated by Django 6.0.6 on 2026-08-24 12:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('google', 'Google'), ('naver', 'Naver'), ('apple', 'Apple')], max_length=20, verbose_name='소셜 제공자')),
                ('provider_user_id', models.CharField(max_length=255, verbose_name='소셜 사용자 ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_accounts', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'ordering': ['created_at'],
                'constraints': [models.UniqueConstraint(fields=('provider', 'provider_user_id'), name='unique_social_account'), models.UniqueConstraint(fields=('user', 'provider'), name='unique_user_social_provider')],
            },
        ),
    ]
