# Generated by Django 6.0.6 on 2026-08-02 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='종료일'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='due_date',
            field=models.DateField(db_index=True, verbose_name='시작일'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='tag',
            field=models.CharField(choices=[('WORK', '업무'), ('PERSONAL', '개인'), ('HEALTH', '건강'), ('STUDY', '공부'), ('ETC', '기타')], default='WORK', max_length=20, verbose_name='태그'),
        ),
    ]
