# Generated by Django 6.0.6 on 2026-08-02 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_todo_end_date_alter_todo_due_date_alter_todo_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='TodoCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_date', models.DateField()),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('todo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='todos.todo')),
            ],
            options={
                'ordering': ['completed_date'],
                'unique_together': {('todo', 'completed_date')},
            },
        ),
    ]
