# Generated by Django 6.0.6 on 2026-08-26 12:47

import todos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_socialaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='is_time_manual',
            field=models.BooleanField(default=False, verbose_name='시간 직접 입력 여부'),
        ),
        migrations.AddField(
            model_name='todo',
            name='todo_time',
            field=models.TimeField(default=todos.models.Get_Current_Time, verbose_name='할 일 시간'),
        ),
    ]
