# Generated by Django 6.0.6 on 2026-08-15 05:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0004_todosomeday'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='todocompletion',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='todo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todos', to=settings.AUTH_USER_MODEL, verbose_name='사용자'),
        ),
        migrations.AlterField(
            model_name='todosomeday',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='someday_todos', to=settings.AUTH_USER_MODEL, verbose_name='사용자'),
        ),
        migrations.AddConstraint(
            model_name='todocompletion',
            constraint=models.UniqueConstraint(fields=('todo', 'completed_date'), name='unique_todo_completion_date'),
        ),
    ]
