# Generated by Django 6.0.6 on 2026-08-18 17:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0006_tag_alter_todo_tag_alter_todosomeday_tag_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='todosomeday',
            options={'ordering': ['is_completed', 'created_at']},
        ),
        migrations.AddField(
            model_name='tag',
            name='is_default',
            field=models.BooleanField(default=False, verbose_name='기본 태그 여부'),
        ),
        migrations.AlterField(
            model_name='todocompletion',
            name='completed_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['user', 'created_at'], name='todos_tag_user_id_03ecee_idx'),
        ),
        migrations.AddIndex(
            model_name='todo',
            index=models.Index(fields=['user', 'due_date'], name='todos_todo_user_id_b502e4_idx'),
        ),
        migrations.AddIndex(
            model_name='todo',
            index=models.Index(fields=['user', 'end_date'], name='todos_todo_user_id_d6607d_idx'),
        ),
        migrations.AddIndex(
            model_name='todocompletion',
            index=models.Index(fields=['todo', 'completed_date'], name='todos_todoc_todo_id_86010b_idx'),
        ),
        migrations.AddIndex(
            model_name='todosomeday',
            index=models.Index(fields=['user', 'created_at'], name='todos_todos_user_id_c096f8_idx'),
        ),
        migrations.AddConstraint(
            model_name='tag',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('user',), name='unique_default_tag_per_user'),
        ),
    ]
